export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇺🇸" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇮🇳" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", flag: "🇮🇳" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", flag: "🇮🇳" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", flag: "🇮🇳" },
  { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ", flag: "🇮🇳" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇧🇷" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
];

// Source languages — all languages supported by Whisper for speech input (STT)
export const SOURCE_LANGUAGES: Language[] = [
  { code: "en",  name: "English",         nativeName: "English",             flag: "🇺🇸" },
  { code: "zh",  name: "Chinese",         nativeName: "中文",                 flag: "🇨🇳" },
  { code: "de",  name: "German",          nativeName: "Deutsch",             flag: "🇩🇪" },
  { code: "es",  name: "Spanish",         nativeName: "Español",             flag: "🇪🇸" },
  { code: "ru",  name: "Russian",         nativeName: "Русский",             flag: "🇷🇺" },
  { code: "ko",  name: "Korean",          nativeName: "한국어",               flag: "🇰🇷" },
  { code: "fr",  name: "French",          nativeName: "Français",            flag: "🇫🇷" },
  { code: "ja",  name: "Japanese",        nativeName: "日本語",               flag: "🇯🇵" },
  { code: "pt",  name: "Portuguese",      nativeName: "Português",           flag: "🇧🇷" },
  { code: "tr",  name: "Turkish",         nativeName: "Türkçe",              flag: "🇹🇷" },
  { code: "pl",  name: "Polish",          nativeName: "Polski",              flag: "🇵🇱" },
  { code: "ca",  name: "Catalan",         nativeName: "Català",              flag: "🇪🇸" },
  { code: "nl",  name: "Dutch",           nativeName: "Nederlands",          flag: "🇳🇱" },
  { code: "ar",  name: "Arabic",          nativeName: "العربية",             flag: "🇸🇦" },
  { code: "sv",  name: "Swedish",         nativeName: "Svenska",             flag: "🇸🇪" },
  { code: "it",  name: "Italian",         nativeName: "Italiano",            flag: "🇮🇹" },
  { code: "id",  name: "Indonesian",      nativeName: "Bahasa Indonesia",    flag: "🇮🇩" },
  { code: "hi",  name: "Hindi",           nativeName: "हिन्दी",               flag: "🇮🇳" },
  { code: "fi",  name: "Finnish",         nativeName: "Suomi",               flag: "🇫🇮" },
  { code: "vi",  name: "Vietnamese",      nativeName: "Tiếng Việt",          flag: "🇻🇳" },
  { code: "he",  name: "Hebrew",          nativeName: "עברית",               flag: "🇮🇱" },
  { code: "uk",  name: "Ukrainian",       nativeName: "Українська",          flag: "🇺🇦" },
  { code: "el",  name: "Greek",           nativeName: "Ελληνικά",            flag: "🇬🇷" },
  { code: "ms",  name: "Malay",           nativeName: "Bahasa Melayu",       flag: "🇲🇾" },
  { code: "cs",  name: "Czech",           nativeName: "Čeština",             flag: "🇨🇿" },
  { code: "ro",  name: "Romanian",        nativeName: "Română",              flag: "🇷🇴" },
  { code: "da",  name: "Danish",          nativeName: "Dansk",               flag: "🇩🇰" },
  { code: "hu",  name: "Hungarian",       nativeName: "Magyar",              flag: "🇭🇺" },
  { code: "ta",  name: "Tamil",           nativeName: "தமிழ்",               flag: "🇮🇳" },
  { code: "no",  name: "Norwegian",       nativeName: "Norsk",               flag: "🇳🇴" },
  { code: "th",  name: "Thai",            nativeName: "ภาษาไทย",             flag: "🇹🇭" },
  { code: "ur",  name: "Urdu",            nativeName: "اردو",                flag: "🇵🇰" },
  { code: "hr",  name: "Croatian",        nativeName: "Hrvatski",            flag: "🇭🇷" },
  { code: "bg",  name: "Bulgarian",       nativeName: "Български",           flag: "🇧🇬" },
  { code: "lt",  name: "Lithuanian",      nativeName: "Lietuvių",            flag: "🇱🇹" },
  { code: "la",  name: "Latin",           nativeName: "Latina",              flag: "🏛️" },
  { code: "mi",  name: "Maori",           nativeName: "Māori",               flag: "🇳🇿" },
  { code: "ml",  name: "Malayalam",       nativeName: "മലയാളം",              flag: "🇮🇳" },
  { code: "cy",  name: "Welsh",           nativeName: "Cymraeg",             flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  { code: "sk",  name: "Slovak",          nativeName: "Slovenčina",          flag: "🇸🇰" },
  { code: "te",  name: "Telugu",          nativeName: "తెలుగు",              flag: "🇮🇳" },
  { code: "fa",  name: "Persian",         nativeName: "فارسی",               flag: "🇮🇷" },
  { code: "lv",  name: "Latvian",         nativeName: "Latviešu",            flag: "🇱🇻" },
  { code: "bn",  name: "Bengali",         nativeName: "বাংলা",               flag: "🇧🇩" },
  { code: "sr",  name: "Serbian",         nativeName: "Српски",              flag: "🇷🇸" },
  { code: "az",  name: "Azerbaijani",     nativeName: "Azərbaycan",          flag: "🇦🇿" },
  { code: "sl",  name: "Slovenian",       nativeName: "Slovenščina",         flag: "🇸🇮" },
  { code: "kn",  name: "Kannada",         nativeName: "ಕನ್ನಡ",               flag: "🇮🇳" },
  { code: "et",  name: "Estonian",        nativeName: "Eesti",               flag: "🇪🇪" },
  { code: "mk",  name: "Macedonian",      nativeName: "Македонски",          flag: "🇲🇰" },
  { code: "br",  name: "Breton",          nativeName: "Brezhoneg",           flag: "🇫🇷" },
  { code: "eu",  name: "Basque",          nativeName: "Euskara",             flag: "🇪🇸" },
  { code: "is",  name: "Icelandic",       nativeName: "Íslenska",            flag: "🇮🇸" },
  { code: "hy",  name: "Armenian",        nativeName: "Հայերեն",             flag: "🇦🇲" },
  { code: "ne",  name: "Nepali",          nativeName: "नेपाली",              flag: "🇳🇵" },
  { code: "mn",  name: "Mongolian",       nativeName: "Монгол",              flag: "🇲🇳" },
  { code: "bs",  name: "Bosnian",         nativeName: "Bosanski",            flag: "🇧🇦" },
  { code: "kk",  name: "Kazakh",          nativeName: "Қазақша",             flag: "🇰🇿" },
  { code: "sq",  name: "Albanian",        nativeName: "Shqip",               flag: "🇦🇱" },
  { code: "sw",  name: "Swahili",         nativeName: "Kiswahili",           flag: "🇹🇿" },
  { code: "gl",  name: "Galician",        nativeName: "Galego",              flag: "🇪🇸" },
  { code: "mr",  name: "Marathi",         nativeName: "मराठी",               flag: "🇮🇳" },
  { code: "pa",  name: "Punjabi",         nativeName: "ਪੰਜਾਬੀ",              flag: "🇮🇳" },
  { code: "si",  name: "Sinhala",         nativeName: "සිංහල",               flag: "🇱🇰" },
  { code: "km",  name: "Khmer",           nativeName: "ភាសាខ្មែរ",           flag: "🇰🇭" },
  { code: "sn",  name: "Shona",           nativeName: "ChiShona",            flag: "🇿🇼" },
  { code: "yo",  name: "Yoruba",          nativeName: "Yorùbá",              flag: "🇳🇬" },
  { code: "so",  name: "Somali",          nativeName: "Soomaali",            flag: "🇸🇴" },
  { code: "af",  name: "Afrikaans",       nativeName: "Afrikaans",           flag: "🇿🇦" },
  { code: "oc",  name: "Occitan",         nativeName: "Occitan",             flag: "🇫🇷" },
  { code: "ka",  name: "Georgian",        nativeName: "ქართული",             flag: "🇬🇪" },
  { code: "be",  name: "Belarusian",      nativeName: "Беларуская",          flag: "🇧🇾" },
  { code: "tg",  name: "Tajik",           nativeName: "Тоҷикӣ",              flag: "🇹🇯" },
  { code: "sd",  name: "Sindhi",          nativeName: "سنڌي",                flag: "🇵🇰" },
  { code: "gu",  name: "Gujarati",        nativeName: "ગુજરાતી",             flag: "🇮🇳" },
  { code: "am",  name: "Amharic",         nativeName: "አማርኛ",               flag: "🇪🇹" },
  { code: "yi",  name: "Yiddish",         nativeName: "ייִדיש",               flag: "🇮🇱" },
  { code: "lo",  name: "Lao",             nativeName: "ລາວ",                 flag: "🇱🇦" },
  { code: "uz",  name: "Uzbek",           nativeName: "O'zbek",              flag: "🇺🇿" },
  { code: "fo",  name: "Faroese",         nativeName: "Føroyskt",            flag: "🇫🇴" },
  { code: "ht",  name: "Haitian Creole",  nativeName: "Kreyòl ayisyen",      flag: "🇭🇹" },
  { code: "ps",  name: "Pashto",          nativeName: "پښتو",                flag: "🇦🇫" },
  { code: "tk",  name: "Turkmen",         nativeName: "Türkmençe",           flag: "🇹🇲" },
  { code: "nn",  name: "Nynorsk",         nativeName: "Nynorsk",             flag: "🇳🇴" },
  { code: "mt",  name: "Maltese",         nativeName: "Malti",               flag: "🇲🇹" },
  { code: "sa",  name: "Sanskrit",        nativeName: "संस्कृतम्",           flag: "🇮🇳" },
  { code: "lb",  name: "Luxembourgish",   nativeName: "Lëtzebuergesch",      flag: "🇱🇺" },
  { code: "my",  name: "Burmese",         nativeName: "မြန်မာဘာသာ",          flag: "🇲🇲" },
  { code: "bo",  name: "Tibetan",         nativeName: "བོད་སྐད་",            flag: "🇨🇳" },
  { code: "tl",  name: "Tagalog",         nativeName: "Tagalog",             flag: "🇵🇭" },
  { code: "mg",  name: "Malagasy",        nativeName: "Malagasy",            flag: "🇲🇬" },
  { code: "as",  name: "Assamese",        nativeName: "অসমীয়া",             flag: "🇮🇳" },
  { code: "tt",  name: "Tatar",           nativeName: "Татарча",             flag: "🇷🇺" },
  { code: "haw", name: "Hawaiian",        nativeName: "ʻŌlelo Hawaiʻi",     flag: "🇺🇸" },
  { code: "ln",  name: "Lingala",         nativeName: "Lingála",             flag: "🇨🇩" },
  { code: "ha",  name: "Hausa",           nativeName: "Hausa",               flag: "🇳🇬" },
  { code: "ba",  name: "Bashkir",         nativeName: "Башҡортса",           flag: "🇷🇺" },
  { code: "jw",  name: "Javanese",        nativeName: "Basa Jawa",           flag: "🇮🇩" },
  { code: "su",  name: "Sundanese",       nativeName: "Basa Sunda",          flag: "🇮🇩" },
  { code: "yue", name: "Cantonese",       nativeName: "粵語",                 flag: "🇭🇰" },
  { code: "or",  name: "Odia",           nativeName: "ଓଡ଼ିଆ",              flag: "🇮🇳" },
  { code: "kok", name: "Konkani",        nativeName: "कोंकणी",              flag: "🇮🇳" },
  { code: "ks",  name: "Kashmiri",       nativeName: "کٲشُر",               flag: "🇮🇳" },
  { code: "sat", name: "Santali",        nativeName: "ᱥᱟᱱᱛᱟᱲᱤ",            flag: "🇮🇳" },
  { code: "mni", name: "Manipuri",       nativeName: "মৈতৈলোন্",           flag: "🇮🇳" },
  { code: "brx", name: "Bodo",           nativeName: "बड़ो",                flag: "🇮🇳" },
  { code: "mai", name: "Maithili",       nativeName: "मैथिली",              flag: "🇮🇳" },
  { code: "doi", name: "Dogri",          nativeName: "डोगरी",               flag: "🇮🇳" },
];

// Target languages — languages supported for speech output (TTS)
export const TARGET_LANGUAGES: Language[] = [
  { code: "en", name: "English",    nativeName: "English",       flag: "🇺🇸" },
  { code: "fr", name: "French",     nativeName: "Français",      flag: "🇫🇷" },
  { code: "de", name: "German",     nativeName: "Deutsch",       flag: "🇩🇪" },
  { code: "es", name: "Spanish",    nativeName: "Español",       flag: "🇪🇸" },
  { code: "pt", name: "Portuguese", nativeName: "Português",     flag: "🇧🇷" },
  { code: "zh", name: "Chinese",    nativeName: "中文",           flag: "🇨🇳" },
  { code: "ja", name: "Japanese",   nativeName: "日本語",         flag: "🇯🇵" },
  { code: "hi", name: "Hindi",      nativeName: "हिन्दी",         flag: "🇮🇳" },
  { code: "it", name: "Italian",    nativeName: "Italiano",      flag: "🇮🇹" },
  { code: "ko", name: "Korean",     nativeName: "한국어",         flag: "🇰🇷" },
  { code: "nl", name: "Dutch",      nativeName: "Nederlands",    flag: "🇳🇱" },
  { code: "pl", name: "Polish",     nativeName: "Polski",        flag: "🇵🇱" },
  { code: "ru", name: "Russian",    nativeName: "Русский",       flag: "🇷🇺" },
  { code: "sv", name: "Swedish",    nativeName: "Svenska",       flag: "🇸🇪" },
  { code: "tr", name: "Turkish",    nativeName: "Türkçe",        flag: "🇹🇷" },
  { code: "tl", name: "Tagalog",    nativeName: "Tagalog",       flag: "🇵🇭" },
  { code: "bg", name: "Bulgarian",  nativeName: "Български",     flag: "🇧🇬" },
  { code: "ro", name: "Romanian",   nativeName: "Română",        flag: "🇷🇴" },
  { code: "ar", name: "Arabic",     nativeName: "العربية",       flag: "🇸🇦" },
  { code: "cs", name: "Czech",      nativeName: "Čeština",       flag: "🇨🇿" },
  { code: "el", name: "Greek",      nativeName: "Ελληνικά",      flag: "🇬🇷" },
  { code: "fi", name: "Finnish",    nativeName: "Suomi",         flag: "🇫🇮" },
  { code: "hr", name: "Croatian",   nativeName: "Hrvatski",      flag: "🇭🇷" },
  { code: "ms", name: "Malay",      nativeName: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "sk", name: "Slovak",     nativeName: "Slovenčina",    flag: "🇸🇰" },
  { code: "da", name: "Danish",     nativeName: "Dansk",         flag: "🇩🇰" },
  { code: "ta", name: "Tamil",      nativeName: "தமிழ்",          flag: "🇮🇳" },
  { code: "uk", name: "Ukrainian",  nativeName: "Українська",    flag: "🇺🇦" },
  { code: "hu", name: "Hungarian",  nativeName: "Magyar",        flag: "🇭🇺" },
  { code: "no", name: "Norwegian",  nativeName: "Norsk",         flag: "🇳🇴" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt",    flag: "🇻🇳" },
  { code: "bn", name: "Bengali",    nativeName: "বাংলা",          flag: "🇮🇳" },
  { code: "th", name: "Thai",       nativeName: "ภาษาไทย",       flag: "🇹🇭" },
  { code: "he", name: "Hebrew",     nativeName: "עברית",         flag: "🇮🇱" },
  { code: "ka", name: "Georgian",   nativeName: "ქართული",       flag: "🇬🇪" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "te", name: "Telugu",     nativeName: "తెలుగు",         flag: "🇮🇳" },
  { code: "gu", name: "Gujarati",   nativeName: "ગુજરાતી",       flag: "🇮🇳" },
  { code: "kn", name: "Kannada",    nativeName: "ಕನ್ನಡ",         flag: "🇮🇳" },
  { code: "ml", name: "Malayalam",  nativeName: "മലയാളം",        flag: "🇮🇳" },
  { code: "mr", name: "Marathi",    nativeName: "मराठी",          flag: "🇮🇳" },
  { code: "pa", name: "Punjabi",    nativeName: "ਪੰਜਾਬੀ",        flag: "🇮🇳" },
  { code: "or", name: "Odia",      nativeName: "ଓଡ଼ିଆ",          flag: "🇮🇳" },
];
