export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGES: Language[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇺🇸" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇮🇳" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", flag: "🇮🇳" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", flag: "🇮🇳" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", flag: "🇮🇳" },
  { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ", flag: "🇮🇳" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇧🇷" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
];

// Source languages — Indian languages supported for speech input (STT)
export const SOURCE_LANGUAGES: Language[] = [
  { code: "hi",  name: "Hindi",     nativeName: "हिन्दी",       flag: "🇮🇳" },
  { code: "bn",  name: "Bengali",   nativeName: "বাংলা",         flag: "🇮🇳" },
  { code: "kn",  name: "Kannada",   nativeName: "ಕನ್ನಡ",        flag: "🇮🇳" },
  { code: "ml",  name: "Malayalam", nativeName: "മലയാളം",        flag: "🇮🇳" },
  { code: "mr",  name: "Marathi",   nativeName: "मराठी",          flag: "🇮🇳" },
  { code: "or",  name: "Odia",      nativeName: "ଓଡ଼ିଆ",         flag: "🇮🇳" },
  { code: "pa",  name: "Punjabi",   nativeName: "ਪੰਜਾਬੀ",        flag: "🇮🇳" },
  { code: "ta",  name: "Tamil",     nativeName: "தமிழ்",          flag: "🇮🇳" },
  { code: "te",  name: "Telugu",    nativeName: "తెలుగు",         flag: "🇮🇳" },
  { code: "gu",  name: "Gujarati",  nativeName: "ગુજરાતી",       flag: "🇮🇳" },
  { code: "en",  name: "English",   nativeName: "English",        flag: "🇮🇳" },
  { code: "as",  name: "Assamese",  nativeName: "অসমীয়া",        flag: "🇮🇳" },
  { code: "ur",  name: "Urdu",      nativeName: "اردو",           flag: "🇮🇳" },
  { code: "ne",  name: "Nepali",    nativeName: "नेपाली",         flag: "🇮🇳" },
  { code: "kok", name: "Konkani",   nativeName: "कोंकणी",         flag: "🇮🇳" },
  { code: "ks",  name: "Kashmiri",  nativeName: "کٲشُر",          flag: "🇮🇳" },
  { code: "sd",  name: "Sindhi",    nativeName: "سنڌي",           flag: "🇮🇳" },
  { code: "sa",  name: "Sanskrit",  nativeName: "संस्कृतम्",      flag: "🇮🇳" },
  { code: "sat", name: "Santali",   nativeName: "ᱥᱟᱱᱛᱟᱲᱤ",        flag: "🇮🇳" },
  { code: "mni", name: "Manipuri",  nativeName: "মৈতৈলোন্",      flag: "🇮🇳" },
  { code: "brx", name: "Bodo",      nativeName: "बड़ो",            flag: "🇮🇳" },
  { code: "mai", name: "Maithili",  nativeName: "मैथिली",         flag: "🇮🇳" },
  { code: "doi", name: "Dogri",     nativeName: "डोगरी",          flag: "🇮🇳" },
];

// Target languages — languages supported for speech output (TTS)
export const TARGET_LANGUAGES: Language[] = [
  { code: "en", name: "English",    nativeName: "English",       flag: "🇺🇸" },
  { code: "fr", name: "French",     nativeName: "Français",      flag: "🇫🇷" },
  { code: "de", name: "German",     nativeName: "Deutsch",       flag: "🇩🇪" },
  { code: "es", name: "Spanish",    nativeName: "Español",       flag: "🇪🇸" },
  { code: "pt", name: "Portuguese", nativeName: "Português",     flag: "🇧🇷" },
  { code: "zh", name: "Chinese",    nativeName: "中文",           flag: "🇨🇳" },
  { code: "ja", name: "Japanese",   nativeName: "日本語",         flag: "🇯🇵" },
  { code: "hi", name: "Hindi",      nativeName: "हिन्दी",         flag: "🇮🇳" },
  { code: "it", name: "Italian",    nativeName: "Italiano",      flag: "🇮🇹" },
  { code: "ko", name: "Korean",     nativeName: "한국어",         flag: "🇰🇷" },
  { code: "nl", name: "Dutch",      nativeName: "Nederlands",    flag: "🇳🇱" },
  { code: "pl", name: "Polish",     nativeName: "Polski",        flag: "🇵🇱" },
  { code: "ru", name: "Russian",    nativeName: "Русский",       flag: "🇷🇺" },
  { code: "sv", name: "Swedish",    nativeName: "Svenska",       flag: "🇸🇪" },
  { code: "tr", name: "Turkish",    nativeName: "Türkçe",        flag: "🇹🇷" },
  { code: "tl", name: "Tagalog",    nativeName: "Tagalog",       flag: "🇵🇭" },
  { code: "bg", name: "Bulgarian",  nativeName: "Български",     flag: "🇧🇬" },
  { code: "ro", name: "Romanian",   nativeName: "Română",        flag: "🇷🇴" },
  { code: "ar", name: "Arabic",     nativeName: "العربية",       flag: "🇸🇦" },
  { code: "cs", name: "Czech",      nativeName: "Čeština",       flag: "🇨🇿" },
  { code: "el", name: "Greek",      nativeName: "Ελληνικά",      flag: "🇬🇷" },
  { code: "fi", name: "Finnish",    nativeName: "Suomi",         flag: "🇫🇮" },
  { code: "hr", name: "Croatian",   nativeName: "Hrvatski",      flag: "🇭🇷" },
  { code: "ms", name: "Malay",      nativeName: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "sk", name: "Slovak",     nativeName: "Slovenčina",    flag: "🇸🇰" },
  { code: "da", name: "Danish",     nativeName: "Dansk",         flag: "🇩🇰" },
  { code: "ta", name: "Tamil",      nativeName: "தமிழ்",          flag: "🇮🇳" },
  { code: "uk", name: "Ukrainian",  nativeName: "Українська",    flag: "🇺🇦" },
  { code: "hu", name: "Hungarian",  nativeName: "Magyar",        flag: "🇭🇺" },
  { code: "no", name: "Norwegian",  nativeName: "Norsk",         flag: "🇳🇴" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt",    flag: "🇻🇳" },
  { code: "bn", name: "Bengali",    nativeName: "বাংলা",          flag: "🇮🇳" },
  { code: "th", name: "Thai",       nativeName: "ภาษาไทย",       flag: "🇹🇭" },
  { code: "he", name: "Hebrew",     nativeName: "עברית",         flag: "🇮🇱" },
  { code: "ka", name: "Georgian",   nativeName: "ქართული",       flag: "🇬🇪" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "te", name: "Telugu",     nativeName: "తెలుగు",         flag: "🇮🇳" },
  { code: "gu", name: "Gujarati",   nativeName: "ગુજરાતી",       flag: "🇮🇳" },
  { code: "kn", name: "Kannada",    nativeName: "ಕನ್ನಡ",         flag: "🇮🇳" },
  { code: "ml", name: "Malayalam",  nativeName: "മലയാളം",        flag: "🇮🇳" },
  { code: "mr", name: "Marathi",    nativeName: "मराठी",          flag: "🇮🇳" },
  { code: "pa", name: "Punjabi",    nativeName: "ਪੰਜਾਬੀ",        flag: "🇮🇳" },
];
